openapi: 3.0.0
info:
  title: Order Management API
  description: API for managing orders in the system
  version: 1.0.0

tags:
  - name: Orders
    description: Order management

paths:
  /api/orders/my-orders:
    get:
      summary: Get user orders
      tags: [Orders]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of user orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/orders/{id}:
    get:
      summary: Get order by ID
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Order ID
      responses:
        200:
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          description: Order ID
        userId:
          type: string
          description: User ID of the person who made the order
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                description: Product ID
              quantity:
                type: integer
                description: Quantity of the product
              price:
                type: number
                description: Price of the product
        totalAmount:
          type: number
          description: Total price for the order
        status:
          type: string
          description: Status of the order (e.g., Pending, Shipped, Delivered)
        createdAt:
          type: string
          format: date-time
          description: Order creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
