openapi: 3.0.0
info:
  title: File Upload API
  description: API for uploading files
  version: 1.0.0

tags:
  - name: Upload
    description: File upload

paths:
  /api/upload:
    post:
      summary: Upload an image
      tags: [Upload]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: Image file to upload
      responses:
        200:
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: URL of uploaded image
        400:
          description: No file uploaded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
      example:
        message: No file uploaded
        code: 400
